linters-settings:
  settings:
    printf:
      funcs:
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
        - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    govet:
      check-shadowing: true
linters:
  enable:
    - gosec
    - gofmt
    - goimports
    - govet
    - errcheck
    - gosimple
    - staticcheck
issues:
  fix: true
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 8m
