version: 2
jobs:
  build:
    docker:
      - image: trussworks/circleci-docker-primary:93fe471597189fed29f1ab2f517fc4c3370f2a77
        environment:
          - TEST_RESULTS: /tmp/test-results
          - GO111MODULE: auto
    steps:
      - checkout
      - restore_cache:
          keys:
            - dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - restore_cache:
          keys:
            - go-mod-sources-v1-{{ checksum "go.sum" }}
      - run:
          name: Adding go binaries to $PATH
          command: |
            echo 'export PATH=${PATH}:~/go/bin' >> $BASH_ENV
            source $BASH_ENV
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
      - run: go get github.com/jstemmer/go-junit-report
      - run: make all
      - save_cache:
          key: dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - save_cache:
          key: go-mod-sources-v1-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"
      - store_test_results:
          path: /tmp/test-results/gotest
