version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
        environment:
          - TEST_RESULTS: /tmp/test-results
    working_directory: /go/src/github.com/trussworks/truss-aws-tools
    steps:
      - checkout
      - restore_cache:
          keys:
            - dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: sudo apt-get install python-pip
      - run: sudo pip install pre-commit
      - run: mkdir -p "${TEST_RESULTS}"
      - run: make all
      - save_cache:
          key: dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - store_test_results:
          path: /tmp/test-results
