version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/trussworks/truss-aws-tools
    steps:
      - checkout
      - restore_cache:
          keys:
            - dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: sudo apt-get install python-pip
      - run: sudo pip install pre-commit
      - run: make all
      - save_cache:
        key: dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
        paths:
          - ~/.cache/pre-commit
