version: 2
jobs:
  build:
    docker:
      - image: trussworks/circleci-docker-primary:4bb9cacfdfa1fbc995e89204f030264843f5bc91
        environment:
          - TEST_RESULTS: /tmp/test-results
    working_directory: ~/go/src/github.com/trussworks/truss-aws-tools
    steps:
      - checkout
      - restore_cache:
          keys:
            - dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
      - restore_cache:
          keys:
            - v1-vendor-{{ checksum "Gopkg.lock" }}
      - run: echo 'export PATH=${PATH}:~/go/bin' >> $BASH_ENV
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: mkdir -p "${TEST_RESULTS}"
      - run: make all
      - save_cache:
          key: dot-cache-pre-commit-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - save_cache:
          key: v1-vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ~/go/pkg/dep
      - store_test_results:
          path: /tmp/test-results
