name: PR Validate

on:
  pull_request:
    branches:
      - main # You can specify the branch you want to trigger on here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Validate
        run: |
          make test

    # Add your build, test, or deployment steps here

